# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [150]:
### YOUR CODE HERE
import numpy as np
mat1 = np.arange(1, 10).reshape((3, 3))
print(f'Матрица 1:\n{mat1}\n')
mat2 = mat1 + np.eye(3)
print(f'Матрица 2:\n{mat2}\n')
mat3 = mat2 @ np.array([1, 2, 3])
print(f'Матрица 3:\n{mat3}\n')
mat4 = mat2.transpose()
print(f'Матрица 4:\n{mat4}\n')
mat5 = np.linalg.inv(mat2)
print(f'Матрица 5:\n{mat5}')

Матрица 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица 2:
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]

Матрица 3:
[15. 34. 53.]

Матрица 4:
[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]

Матрица 5:
[[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01  2.22044605e-17]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]


## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [151]:
### YOUR CODE HERE
m = np.array([[2, 2],
              [1, 3]])
eig_vals, eig_vectors = np.linalg.eig(m)
print(f'Собственные значения: {eig_vals}')
print(f'Собсбвенный вектор:\n {eig_vectors}')

Собственные значения: [1. 4.]
Собсбвенный вектор:
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [152]:
### YOUR CODE HERE
# Возмем единичную матрицу:
mat = np.eye(3)
# Для избавления от нулей прибавим к каждой строке другие строки, умноженные на случайное целое число:
mat[0] = mat[0] + mat[1]*np.random.randint(1, 10) + mat[2]*np.random.randint(1, 10)
mat[1] = mat[1] + mat[0]*np.random.randint(1, 10) + mat[2]*np.random.randint(1, 10)
mat[2] = mat[2] + mat[0]*np.random.randint(1, 10) + mat[1]*np.random.randint(1, 10)
print(f'Матрица с единичным определителем:\n {mat}')
print(f'Определитель матрицы: {np.linalg.det(mat):.2f}')

Матрица с единичным определителем:
 [[  1.   3.   5.]
 [  4.  13.  28.]
 [ 24.  76. 153.]]
Определитель матрицы: 1.00


In [172]:
v = np.array([1, 2, 3])
A = np.array([[1, 2], [3, 4], [5, 6]])
print(v)
print()
print(A)
v @ A
#A @ v

[1 2 3]

[[1 2]
 [3 4]
 [5 6]]


array([22, 28])

In [176]:
print(v)
print()
print(A)
print()
print(np.dot(v, A))
print(np.matmul(v, A))

[1 2 3]

[[1 2]
 [3 4]
 [5 6]]

[22 28]
[22 28]


In [180]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)
np.dot(A, B)  # вернёт матрицу: [[1*5 + 2*7, 1*6 + 2*8], [3*5 + 4*7, 3*6 + 4*8]]

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [181]:
# создание двух матриц
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)
# выполнение матричного умножения с помощью matmul()
result = np.matmul(A, B)
print(result)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [167]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[1, 2], [3, 4]])
print(m1)
print()
print(m2)
print()
print(np.dot(m1, m2))

[[1 2]
 [3 4]]

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]


In [182]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1)
print(v2)
print(np.dot(v1, v2))
print(np.matmul(v1, v2))

[1 2 3]
[4 5 6]
32
32
